#! /bin/bash

brew install \
     autoconf \
     bzip2 \
     gmp \
     icu4c \
     libiconv \
     libjpeg \
     libpng \
     libpq \
     libxml2 \
     libzip \
     oniguruma \
     pkg-config \
     zlib

. ~/.phpbrew/bashrc

if [ $# != 1 ]; then
    phpbrew known

    exit
fi

brew_pkg_config() {
    brew info $1 | sed -n 's/.*PKG_CONFIG_PATH="\(.*\)"/\1/p'
}

phpbrew install -j $(sysctl -n hw.ncpu) $1 +bz2 +fpm +pear || exit
phpbrew use $1

for ext in \
	ctype \
	curl \
	fileinfo \
	filter \
	gd \
	gmp \
	iconv:libiconv/iconv \
	intl:icu4c/pkg_config \
	json \
	mbstring \
	opcache \
	openssl/pkg_config \
	pcntl \
	pdo \
	pdo_pgsql:libpq/pdo-pgsql \
	posix \
	readline \
	soap \
	zip \
	zlib; do
    e=${ext%%/*}

    case ${ext} in
	*/pkg_config)
	    PKG_CONFIG_PATH="$(brew_pkg_config ${e##*:})" phpbrew extension install ${e%%:*}
	    ;;
	*/*)
	    phpbrew extension install ${e%%:*} -- --with-${ext##*/}=$(brew --prefix ${e##*:})
	    ;;
	*)
	    phpbrew extension install ${e}
	    ;;
    esac
done
